Repository ProMedi24-1/HordeSurvivalGame, pull requests merged in 2024-05, with the labels that each got.

#10 feat: [#9] Added DevMenus using ImGui
  .gitignore
  project/.godot/global_script_class_cache.cfg
  project/project.godot
  project/scenes/dev_menus/dev_menus.tscn
  project/scenes/imgui/imgui_test.tscn
  project/scenes/levels/test_level.tscn
  project/scripts/dev_menus/dev_menubase.gd
  project/scripts/dev_menus/dev_overview.gd
  project/scripts/dev_menus/dev_ui.gd
  project/scripts/dev_menus/submenus/dev_profiler.gd
  project/scripts/dev_menus/submenus/dev_statistics.gd
  project/scripts/imgui/imgui_test.gd
Labels: enhancement

#15 #14 Disable Codesign in Export Presets
  project/export_presets.cfg
Labels: bug

#23 [#21] Added POC-Content to Project
  project/poc_content/code/Charakter.gd
  project/poc_content/code/Container.gd
  project/poc_content/code/EnemySpawnLogic.gd
  project/poc_content/code/Icon.gd
  project/poc_content/code/WeaponLogic.gd
  project/poc_content/code/bullet.gd
  project/poc_content/code/score_text.gd
  project/poc_content/code/ui.gd
  project/poc_content/code/ui_container.gd
  project/poc_content/code/weird_crawler.gd
  project/poc_content/code/zombie.gd
  project/poc_content/images/csm_duerre-boden-ausgetrocknet-patagonien-argentinien-WW191953-c-michel-gunther-wwf_dc70a6a1c3.jpg
  project/poc_content/images/csm_duerre-boden-ausgetrocknet-patagonien-argentinien-WW191953-c-michel-gunther-wwf_dc70a6a1c3.jpg.import
  project/poc_content/images/icon.svg
  project/poc_content/images/icon.svg.import
  project/poc_content/images/tile_0110.png
  project/poc_content/images/tile_0110.png.import
  project/poc_content/images/vecteezy_simple-tree-icon_12665403.jpg
  project/poc_content/images/vecteezy_simple-tree-icon_12665403.jpg.import
  project/poc_content/scenes/bullet.tscn
  project/poc_content/scenes/charakter.tscn
  project/poc_content/scenes/enemy_spawn_logic.tscn
  project/poc_content/scenes/tree.tscn
  project/poc_content/scenes/ui.tscn
  project/poc_content/scenes/weird_crawler.tscn
  project/poc_content/scenes/world.tscn
  project/poc_content/scenes/zombie.tscn
  project/poc_content/ui_themes/new_theme.tres
  project/poc_content/ui_themes/skill_container.tres
  project/poc_content/world.gd
Labels: enhancement

#25 Major rework of player and main menu
  project/.godot/global_script_class_cache.cfg
  project/assets/light/2d_point.webp
  project/assets/light/2d_point.webp.import
  project/assets/shaders/ShadowShader.gdshader
  project/assets/shaders/testshader.gdshader
  project/assets/sprites/level/testlevel_set.tres
  project/assets/sprites/level/testlevel_tilemap.png
  project/assets/sprites/level/testlevel_tilemap.png.import
  project/assets/sprites/player/player.png
  project/assets/sprites/player/player.png.import
  project/project.godot
  project/scenes/components/health_component.tscn
  project/scenes/components/player_movement_component.tscn
  project/scenes/components/stats_component.tscn
  project/scenes/dev_menus/dev_menus.tscn
  project/scenes/game/game_entry.tscn
  project/scenes/game/game_root.tscn
  project/scenes/levels/test_level.tscn
  project/scenes/levels/tiles/collision_tile.tscn
  project/scenes/player/player.tscn
  project/scripts/components/health_component.gd
  project/scripts/components/player_movement_component.gd
  project/scripts/components/stats_component.gd
  project/scripts/dev_menus/dev_overview.gd
  project/scripts/dev_menus/submenus/dev_player.gd
  project/scripts/dev_menus/submenus/dev_profiler.gd
  project/scripts/game/game_entry.gd
  project/scripts/game/game_manager.gd
  project/scripts/game/game_root.gd
  project/scripts/levels/level_base.gd
  project/scripts/player/player.gd
  project/scripts/player/player_character.gd
  project/scripts/ui/menus/main_menu/menu_root.gd
Labels: enhancement

#31 Implementation of EntityAdmin
  project/.godot/global_script_class_cache.cfg
  project/content/component/entity/enemy_movement_component.gd
  project/content/component/entity/entity_base_component.gd
  project/content/component/entity/entity_base_component.tscn
  project/content/debug/debug_entity_inspector.gd
  project/content/debug/debug_menu_bar.gd
  project/content/entity/enemy/goblin_enemy.tscn
  project/content/entity/player/player.tscn
  project/content/global/entity_admin.gd
  project/content/global/game_globals.gd
  project/content/global/scene_admin.gd
  project/content/global/state_admin.gd
  project/content/global/test.gd
Labels: enhancement

#33 Added kitten sprite for player
  project/assets/sprites/player/kitten.png
  project/assets/sprites/player/kitten.png.import
  project/content/entity/player/player.tscn
  project/content/global/entity_admin.gd
  project/content/level/test_level.tscn
Labels: enhancement

#40 added tree sprite
  project/assets/sprites/level/Tree.png
  project/assets/sprites/level/Tree.png.import
  project/content/level/test_level.tscn
  project/content/ui/main_menu/main_menu.gd
Labels: enhancement, Art-Team

#44 PlayButton Test
  project/content/ui/main_menu/main_menu.gd
  project/content/ui/main_menu/main_menu.tscn
Labels: enhancement, Art-Team
